# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.CharField(max_length=10),
        ),
    ]
