# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0002_auto_20170730_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='high',
            field=models.CharField(default=122, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='low',
            field=models.CharField(default=122, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='perct',
            field=models.CharField(default=122, max_length=10),
            preserve_default=False,
        ),
    ]
