# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0006_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='tp',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
