# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0009_auto_20170817_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
