# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0010_auto_20170817_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_id',
            field=models.AutoField(default=66666, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
