# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0011_auto_20170817_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prev',
            field=models.CharField(default=111, max_length=10),
            preserve_default=False,
        ),
    ]
